### ISSUE TITLE
`.node_modules.ember-try` folder included in v1.0.3 release

### ISSUE THREAD

**Issue by Turbo87** [pzuraq/ember-legacy-class-shim#13]
I just noticed that the v1.0.3 release includes the `.node_modules.ember-try` folder, which causes the package size to be **a lot** bigger than necessary 😉

**Comment by jtjeferreira** [comment]
I also noticed this. could you release a new version without this? thx

**Comment by pzuraq** [comment]
Fixed in v1.0.4, thanks for the fix @Turbo87!
